import type { Metadata } from "next";
import { Playfair_Display, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/header";
import HeroSection from "@/widgets/hero/hero-section";
import AboutSection from "@/widgets/about/about-section";
import ServiceSection from "@/widgets/service/service-section";
import ReviewSection from "@/widgets/review/review-section";
import PhotoSection from "@/widgets/photo/photo-section";
import Footer from "@/widgets/footer/footer";


const playFairDisplay = Playfair_Display ({
    variable: "--font-playfair",
    subsets: ["latin", "cyrillic"],
    weight: ["400", "500", "600", "700", "800", "900"],


});

const openSans = Open_Sans ({
    variable: "--font-open-sans",
    subsets: ["latin", "cyrillic"],
    weight: ["300", "400", "500", "600", "700",],


});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${playFairDisplay.variable}  font-sans bg-blue-950  text-white/60 antialiased`}>
      <Header/>
      <HeroSection/>
      <AboutSection/>
      <ServiceSection/>
      <ReviewSection/>
      <PhotoSection/>
      <Footer/>
        {children}
      </body>
    </html>
  );
}





























